# -*- coding: utf-8 -*-
"""02_text_augmentation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0DijjbPAo07wAO5fVZzK1Zz5vmh1hmF

#1. 데이터 로드
"""

import pandas as pd

train = pd.read_csv('../data/train_sampled.csv')
test  = pd.read_csv('../data/test_sampled.csv')

print(f"원본 train: {train.shape}, test: {test.shape}")

"""#2. GPT API 설정"""

from openai import OpenAI
import os
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

"""#3. 질문 증강 함수"""

import json

def augment_question(context, question):
  """gpt-3.5-turbo를 이용해 문맥에 맞는 새로운 질문 2개를 생성합니다."""
  prompt = f"""
당신은 한국어 QA 데이터셋을 확장하는 데이터 엔지니어입니다.
제공된 [문맥]과 [기존 질문]을 바탕으로, 문맥에서 정답을 찾을 수 있으면서 기존 질문과 의미는 같고 표현이나 문장 구조가 다른 새로운 질문 2개를 생성하세요.

[문맥]: {context}
[기존 질문]: {question}

출력 형식은 반드시 아래와 같은 파이썬/JSON 리스트 형식이어야 합니다. 다른 설명은 하지마세요.
["새로운 질문 1","새로운 질문 2"]
"""

  try:
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages= [
            {
                "role": "system",
                "content": "너는 자연어 처리 데이터 증강 전문가야. 오직 JSON Array 형식으로만 답변해.",
            },
            {"role":"user","content":prompt},
        ],
        temperature=0.7,
        max_tokens=256
    )
    result_text = response.choices[0].message.content.strip()
    return json.loads(result_text)
  except Exception as e:
    print(f"Error: {e}")
    return []


df = train
output_file = "/content/sample_data/train_augmented.csv"

augmented_records = []

for idx, row in tqdm(df.iterrows(), total=len(df)):
    augmented_records.append(row.to_dict())
    new_questions = augment_question(row["context"], row["question"])


    for i , new_q in enumerate(new_questions):
        new_row = row.to_dict()
        new_row["question"] = new_q
        new_row["id"] = f"{row['id']}_{i+1}"
        augmented_records.append(new_row)



augmented_df = pd.DataFrame(augmented_records)
augmented_df.to_csv(output_file, index=False, encoding="utf-8-sig")

print(f"\n증강 완료 데이터 수가 {len(df)}개에서 {len(augmented_df)}개로 확장되었습니다.")
print(f"결과가 '{output_file}'에 저장되었습니다.")

"""#4. 증강 실행 & 저장"""

from tqdm import tqdm

output_file       = '../data/train_augmented.csv'
augmented_records = []

for idx, row in tqdm(train.iterrows(), total=len(train)):
    augmented_records.append(row.to_dict())

    new_questions = augment_question(row['context'], row['question'])

    for i, new_q in enumerate(new_questions):
        new_row             = row.to_dict()
        new_row['question'] = new_q
        new_row['id']       = f"{row['id']}_{i+1}"
        augmented_records.append(new_row)

augmented_df = pd.DataFrame(augmented_records)
augmented_df.to_csv(output_file, index=False, encoding='utf-8-sig')

print(f"\n증강 완료: {len(train)}개 → {len(augmented_df)}개")
print(f"저장 위치: {output_file}")