# -*- coding: utf-8 -*-
"""03_augmented_T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-gkNttcMPocHXUjHZIPxCICWc0jrFFJ

#1. 데이터 로드
"""

import pandas as pd
import ast

train = pd.read_csv('../data/train_augmented.csv')
test  = pd.read_csv('../data/test_sampled.csv')

print(f"증강 train: {train.shape}, test: {test.shape}")

"""#2. 토크나이저 & GPU device"""

import torch
from transformers import PreTrainedTokenizerFast

device    = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tokenizer = PreTrainedTokenizerFast.from_pretrained("paust/pko-t5-small")

print(f"device: {device}")

"""#3. Dataset"""

from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, data, tokenizer):
        self.data      = data
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        question = self.data.iloc[idx]['question']
        context  = self.data.iloc[idx]['context']
        answer   = self.data.iloc[idx]['answers']

        if isinstance(answer, str):
            answer = ast.literal_eval(answer)

        input_text = 'question: {} context: {}'.format(question, context)

        feature = self.tokenizer(
            input_text,
            return_tensors='pt',
            padding='max_length',
            truncation=True,
            max_length=512
        )
        target = self.tokenizer(
            answer['text'][0],
            return_tensors='pt',
            padding='max_length',
            truncation=True,
            max_length=128
        )

        labels = target['input_ids'].squeeze()
        labels[labels == self.tokenizer.pad_token_id] = -100

        return {
            'input_ids':      feature['input_ids'].squeeze(),
            'attention_mask': feature['attention_mask'].squeeze(),
            'labels':         labels
        }


train_data = CustomDataset(train, tokenizer)
test_data  = CustomDataset(test,  tokenizer)

train_loader = DataLoader(train_data, batch_size=4, shuffle=True)
test_loader  = DataLoader(test_data,  batch_size=4, shuffle=False)

"""#4. T5 모델 & 옵티마이저"""

import torch.optim as optim
from transformers import T5ForConditionalGeneration

model     = T5ForConditionalGeneration.from_pretrained("paust/pko-t5-small").to(device)
optimizer = optim.Adam(model.parameters(), lr=5e-5)

"""#5. 학습 함수"""

from tqdm import tqdm

def run_train_loop(model, train_loader, optimizer, device):
    model.train()
    train_loss   = 0
    progress_bar = tqdm(train_loader, unit='batch', total=len(train_loader), mininterval=1)

    for idx, batch in enumerate(progress_bar):
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels']['input_ids'].squeeze(1).to(device)

        optimizer.zero_grad()
        output = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss   = output.loss
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        progress_bar.set_postfix({'train_loss': train_loss / (idx + 1)})

    return train_loss / len(train_loader)

"""#6. 평가 함수 ( + EM + F1 )"""

# pip install evaluate
import evaluate

metric = evaluate.load("squad")

def run_evaluate_loop(model, test_loader, device, test_df):
    model.eval()
    test_loss   = 0
    predictions = []
    references  = []
    wrong_case = []
    with torch.no_grad():
        progress_bar = tqdm(test_loader, unit='batch', total=len(test_loader), mininterval=1)

        for idx, batch in enumerate(progress_bar):
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['labels'].to(device)

            output     = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            test_loss += output.loss.item()

            generated      = model.generate(input_ids=input_ids, max_length=64)
            decoded_preds  = tokenizer.batch_decode(generated, skip_special_tokens=True)
            labels_for_decode = labels.clone()
            labels_for_decode[labels_for_decode == -100] = tokenizer.pad_token_id
            decoded_labels = tokenizer.batch_decode(labels_for_decode, skip_special_tokens=True)

            for i, (pred, label) in enumerate(zip(decoded_preds, decoded_labels)):
                uid = str(idx * test_loader.batch_size + i)
                data_idx = idx * test_loader.batch_size + i
                predictions.append({"id": uid, "prediction_text": pred})
                references.append({"id": uid, "answers": {"text": [label], "answer_start": [0]}})


                if pred.strip() != label.strip():
                    answer = test_df.iloc[data_idx]['answers']
                    if isinstance(answer, str):
                        answer = ast.literal_eval(answer)

                    wrong_case.append({
                        'question': test_df.iloc[data_idx]['question'],
                        'context': test_df.iloc[data_idx]['context'],
                        'answer': label,
                        'pred' : pred
                    })



            progress_bar.set_postfix({'test_loss': test_loss / (idx + 1)})

    result = metric.compute(predictions=predictions, references=references)
    return test_loss / len(test_loader), result['exact_match'], result['f1'], wrong_case

"""#7. 루프"""

import numpy as np

num_epochs = 10
model_name = "augmented_T5"
min_loss   = np.inf
history    = {'train_loss': [], 'test_loss': [], 'em': [], 'f1': []}

for epoch in range(num_epochs):
    train_loss = run_train_loop(model, train_loader, optimizer, device)
    test_loss, em, f1, wrong_case = run_evaluate_loop(model, test_loader, device, test)

    if test_loss < min_loss:
        min_loss = test_loss
        last_wrong_case = wrong_case
        torch.save(model.state_dict(), f'/content/sample_data/{model_name}.pth')

    history['train_loss'].append(train_loss)
    history['test_loss'].append(test_loss)
    history['em'].append(em)
    history['f1'].append(f1)

    print(f"Epoch {epoch+1}/{num_epochs} | Train Loss: {train_loss:.4f} | Test Loss: {test_loss:.4f} | EM: {em:.1f}% | F1: {f1:.1f}%")

wrong_case_df = pd.DataFrame(last_wrong_case)
wrong_case_df.to_csv('/content/sample_data/wrong_cases.csv',index=False, encoding='utf-8-sig')
print(f"\n틀린 케이스 {len(wrong_case_df)}개 저장")

"""#8. 시각화"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].plot(history['train_loss'], label='train')
axes[0].plot(history['test_loss'],  label='test')
axes[0].set_title('Loss')
axes[0].set_xlabel('Epoch')
axes[0].legend()

axes[1].plot(history['em'], color='green')
axes[1].set_title('Exact Match')
axes[1].set_xlabel('Epoch')

axes[2].plot(history['f1'], color='orange')
axes[2].set_title('F1 Score')
axes[2].set_xlabel('Epoch')

plt.tight_layout()
plt.show()
