# -*- coding: utf-8 -*-
"""04_error_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMvDaba75qmwdkJBSX7m840cVAzCXeSq

# 1. import 및 데이터 로드
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

wrong = pd.read_csv("/content/sample_data/wrong_cases.csv")

"""#2. 오류와 정답 비교"""

for idx, row in wrong.iterrows():
    print(f"질문:  {row['question']}")
    print(f"정답:  {row['answer']}")
    print(f"예측:  {row['pred']}")
    print("-" * 50)

"""#3. 데이터 정리 및 시각화"""

wrong['answer_len'] = wrong['answer'].str.len()
wrong['pred_len'] = wrong['pred'].str.len()

print(wrong[['answer_len','pred_len']].describe())

sns.histplot(wrong['answer_len'], label='answer', color='blue')
sns.histplot(wrong['pred_len'], label='pred', color='red')
plt.legend()
plt.show()